import type { Metadata } from 'next';
import { inter, title_fonts } from '@/config/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={title_fonts.className}>{children}</body>
    </html>
  );
}
